export const EXPERIENCE_CATALOG = [
  {
    id: 'dots-and-boxes',
    name: 'Dots & Boxes',
    shortName: 'Dots',
    path: '/dots-and-boxes',
    kind: 'Strategy',
    status: 'Live',
    accent: 'var(--forest)',
    description: 'The original online board game with lobbies, ranked play, replays, achievements, and local matches.',
    features: ['Online lobby', 'Local play', 'ELO ranks', 'Replays'],
    navItems: [
      { to: '/dots-and-boxes', label: 'Home' },
      { to: '/lobby', label: 'Lobby' },
      { to: '/local', label: 'Local' },
      { to: '/leaderboard', label: 'Ranks' },
      { to: '/history', label: 'History' },
      { to: '/achievements', label: 'Awards' },
    ],
    routePrefixes: [
      '/dots-and-boxes',
      '/lobby',
      '/local',
      '/match',
      '/leaderboard',
      '/history',
      '/replay',
      '/achievements',
    ],
  },
  {
    id: 'connect4',
    name: 'Connect 4',
    shortName: 'Connect 4',
    path: '/connect4',
    kind: 'Strategy',
    status: 'Live',
    accent: 'var(--crimson)',
    description: 'Classic 4-in-a-row with custom colors. Play online or locally.',
    features: ['Online lobby', 'Local play', 'Custom colors'],
    navItems: [
      { to: '/connect4', label: 'Home' },
      { to: '/connect4/local', label: 'Local' },
    ],
    routePrefixes: [
      '/connect4',
    ],
  },
  {
    id: 'tictactoe',
    name: 'Tic-Tac-Toe',
    shortName: 'Tic-Tac-Toe',
    path: '/tictactoe',
    kind: 'Strategy',
    status: 'Live',
    accent: 'var(--ochre)',
    description: 'Classic 3x3 Tic-Tac-Toe. Play online or locally.',
    features: ['Online lobby', 'Local play'],
    navItems: [
      { to: '/tictactoe', label: 'Home' },
      { to: '/tictactoe/local', label: 'Local' },
    ],
    routePrefixes: [
      '/tictactoe',
    ],
  },
  {
    id: 'chess',
    name: 'Chess',
    shortName: 'Chess',
    path: '/chess',
    kind: 'Strategy',
    status: 'Live',
    accent: 'var(--ink)',
    description: 'Classic Chess. Play online or locally with board flipping.',
    features: ['Online lobby', 'Local play', 'Board flip'],
    navItems: [
      { to: '/chess', label: 'Home' },
      { to: '/chess/local', label: 'Local' },
    ],
    routePrefixes: [
      '/chess',
    ],
  },
  {
    id: 'paper-io',
    name: 'Paper.io',
    shortName: 'Paper.io',
    path: '/paper-io',
    kind: 'Arcade',
    status: 'Live',
    accent: 'var(--crimson)',
    immersive: true,
    description: 'A native Axiom territory-control arcade run with bots, selectable modes, live stats, and local awards.',
    features: ['Live bots', 'Modes', 'Stats', 'Awards'],
    navItems: [
      { to: '/paper-io', label: 'Play' },
      { to: '/paper-io#custom', label: 'Modes' },
      { to: '/paper-io#stats', label: 'Stats' },
      { to: '/paper-io#ach', label: 'Awards' },
    ],
    routePrefixes: ['/paper-io'],
  },
  {
    id: 'battleships',
    name: 'Battleships',
    shortName: 'Battleships',
    path: '/battleships',
    kind: 'Strategy',
    status: 'Live',
    accent: 'var(--forest)',
    description: 'Classic naval combat game. Strategically place your fleet and sink the enemy before they sink you.',
    features: ['Local play', 'Smart AI opponent'],
    navItems: [
      { to: '/battleships', label: 'Play' },
    ],
    routePrefixes: ['/battleships'],
  },
  {
    id: 'memory-match',
    name: 'Memory Match',
    shortName: 'Memory',
    path: '/memory-match',
    kind: 'Puzzle',
    status: 'Live',
    accent: 'var(--ochre)',
    description: 'A classic memory game. Flip cards to find matching pairs.',
    features: ['Local play', 'Move tracking'],
    navItems: [
      { to: '/memory-match', label: 'Play' },
    ],
    routePrefixes: ['/memory-match'],
  },
  {
    id: 'snake',
    name: 'Snake',
    shortName: 'Snake',
    path: '/snake',
    kind: 'Arcade',
    status: 'Live',
    accent: 'var(--forest)',
    description: 'Classic Snake game. Eat food, grow longer, avoid walls and yourself.',
    features: ['Local play', 'High score'],
    navItems: [
      { to: '/snake', label: 'Play' },
    ],
    routePrefixes: ['/snake'],
  },
  {
    id: 'click-the-target',
    name: 'Click the Target',
    shortName: 'Target',
    path: '/click-the-target',
    kind: 'Arcade',
    status: 'Live',
    accent: 'var(--crimson)',
    description: 'Click the target as many times as you can in 30 seconds.',
    features: ['Local play', 'Best score'],
    navItems: [
      { to: '/click-the-target', label: 'Play' },
    ],
    routePrefixes: ['/click-the-target'],
  },
  {
    id: 'sequence-memory',
    name: 'Sequence Memory',
    shortName: 'Sequence',
    path: '/sequence-memory',
    kind: 'Arcade',
    status: 'Live',
    accent: 'var(--ochre)',
    description: 'Repeat the pattern of lights and sounds. It gets longer every round!',
    features: ['Local play', 'Best level'],
    navItems: [
      { to: '/sequence-memory', label: 'Play' },
    ],
    routePrefixes: ['/sequence-memory'],
  },
  {
    id: 'guess-the-number',
    name: 'Guess the Number',
    shortName: 'Guess',
    path: '/guess-the-number',
    kind: 'Arcade',
    status: 'Live',
    accent: 'var(--ochre)',
    description: 'Find the hidden number. Use logic and higher/lower feedback to guess it in the fewest tries.',
    features: ['Local play', 'Best score'],
    navItems: [
      { to: '/guess-the-number', label: 'Play' },
    ],
    routePrefixes: ['/guess-the-number'],
  },
  {
    id: 'quick-math',
    name: 'Quick Math',
    shortName: 'Math',
    path: '/quick-math',
    kind: 'Arcade',
    status: 'Live',
    accent: 'var(--crimson)',
    description: 'Solve as many math problems as you can in 60 seconds.',
    features: ['Local play', 'Best score'],
    navItems: [
      { to: '/quick-math', label: 'Play' },
    ],
    routePrefixes: ['/quick-math'],
  },
  {
    id: 'typing-speed',
    name: 'Typing Speed',
    shortName: 'Typing',
    path: '/typing-speed',
    kind: 'Arcade',
    status: 'Live',
    accent: 'var(--forest)',
    description: 'Test your typing speed and accuracy. Type the phrases as fast as you can.',
    features: ['Local play', 'Best WPM'],
    navItems: [
      { to: '/typing-speed', label: 'Play' },
    ],
    routePrefixes: ['/typing-speed'],
  },
  {
    id: 'speed-math',
    name: 'Speed Math',
    shortName: 'Math',
    path: '/speed-math',
    kind: 'Arcade',
    status: 'Live',
    accent: 'var(--ochre)',
    description: 'Test your mental math speed. Solve as many basic math problems as you can in 60 seconds.',
    features: ['Local play', 'Best score'],
    navItems: [
      { to: '/speed-math', label: 'Play' },
    ],
    routePrefixes: ['/speed-math'],
  },
  {
    id: 'reaction-timer',
    name: 'Reaction Timer',
    shortName: 'Reaction',
    path: '/reaction-timer',
    kind: 'Arcade',
    status: 'Live',
    accent: 'var(--crimson)',
    description: 'Test your reflexes. Click as fast as you can when the color changes.',
    features: ['Local play', 'Best times'],
    navItems: [
      { to: '/reaction-timer', label: 'Play' },
    ],
    routePrefixes: ['/reaction-timer'],
  },
  {
    id: 'word-scramble',
    name: 'Word Scramble',
    shortName: 'Scramble',
    path: '/word-scramble',
    kind: 'Arcade',
    status: 'Live',
    accent: 'var(--forest)',
    description: 'Unscramble as many words as you can in 60 seconds.',
    features: ['Local play', 'Best score'],
    navItems: [
      { to: '/word-scramble', label: 'Play' },
    ],
    routePrefixes: ['/word-scramble'],
  },
  {
    id: 'whack-a-mole',
    name: 'Whack-A-Mole',
    shortName: 'Whack-A-Mole',
    path: '/whack-a-mole',
    kind: 'Arcade',
    status: 'Live',
    accent: 'var(--ochre)',
    description: 'Whack the moles as quickly as you can before time runs out.',
    features: ['Local play', 'Best score'],
    navItems: [
      { to: '/whack-a-mole', label: 'Play' },
    ],
    routePrefixes: ['/whack-a-mole'],
  },
  {
    id: 'guess-the-number',
    name: 'Guess the Number',
    shortName: 'Guess',
    path: '/guess-the-number',
    kind: 'Arcade',
    status: 'Live',
    accent: 'var(--ochre)',
    description: 'Guess the secret number in the fewest attempts possible.',
    features: ['Local play', 'Best attempts'],
    navItems: [
      { to: '/guess-the-number', label: 'Play' },
    ],
    routePrefixes: ['/guess-the-number'],
  },
  {
    id: 'rock-paper-scissors',
    name: 'Rock Paper Scissors',
    shortName: 'RPS',
    path: '/rock-paper-scissors',
    kind: 'Arcade',
    status: 'Live',
    accent: 'var(--forest)',
    description: 'Classic Rock Paper Scissors. Play against the computer and build your winning streak.',
    features: ['Local play', 'Winning streak'],
    navItems: [
      { to: '/rock-paper-scissors', label: 'Play' },
    ],
    routePrefixes: ['/rock-paper-scissors'],
  },
  {
    id: 'district-exchange',
    name: 'District Exchange',
    shortName: 'District',
    path: '/district-exchange',
    kind: 'Strategy',
    status: 'Live',
    accent: 'var(--forest)',
    description: 'Buy, trade, and upgrade districts. Bankrupt your opponents in this classic property trading experience with a modern twist.',
    features: ['Local match'],
    navItems: [
      { to: '/district-exchange', label: 'Home' },
      { to: '/district-exchange/local', label: 'Local' },
    ],
    routePrefixes: ['/district-exchange'],
  },
  {
    id: 'speed-math',
    name: 'Speed Math',
    shortName: 'Math',
    path: '/speed-math',
    kind: 'Arcade',
    status: 'Live',
    accent: 'var(--ochre)',
    description: 'Solve as many basic math problems as you can in 60 seconds.',
    features: ['Local play', 'Best score'],
    navItems: [
      { to: '/speed-math', label: 'Play' },
    ],
    routePrefixes: ['/speed-math'],
  },
  {
    id: 'circuit-maker',
    name: 'Circuit Maker',
    shortName: 'Circuits',
    path: '/circuit-maker',
    kind: 'Builder',
    status: 'Live',
    accent: 'var(--ochre)',
    immersive: true,
    description: 'A native Axiom logic-circuit workspace with gates, switches, LEDs, saving, loading, samples, and PNG export.',
    features: ['Logic gates', 'Projects', 'Samples', 'PNG export'],
    navItems: [
      { to: '/circuit-maker', label: 'Builder' },
      { to: '/circuit-maker#palette', label: 'Palette' },
      { to: '/circuit-maker#sampleBtn', label: 'Sample' },
      { to: '/circuit-maker#projectList', label: 'Projects' },
      { to: '/circuit-maker#exportPng', label: 'Export' },
    ],
    routePrefixes: ['/circuit-maker'],
  },
  {
    id: 'color-match',
    name: 'Color Match',
    shortName: 'Colors',
    path: '/color-match',
    kind: 'Arcade',
    status: 'Live',
    accent: 'var(--crimson)',
    description: 'Test your brain. Does the word match the color?',
    features: ['Local play', 'Best score'],
    navItems: [
      { to: '/color-match', label: 'Play' },
    ],
    routePrefixes: ['/color-match'],
  },
  {
    id: 'speed-grid',
    name: 'Speed Grid',
    shortName: 'Speed Grid',
    path: '/speed-grid',
    kind: 'Arcade',
    status: 'Live',
    accent: 'var(--ochre)',
    description: 'Click the numbers from 1 to 25 as fast as you can.',
    features: ['Local play', 'Best time'],
    navItems: [
      { to: '/speed-grid', label: 'Play' },
    ],
    routePrefixes: ['/speed-grid'],
  },
];

export const DEFAULT_EXPERIENCE = {
  id: 'axiom',
  name: 'Axiom',
  shortName: 'Axiom',
  path: '/',
  kind: 'Hub',
  status: 'Live',
  navItems: [
    { to: '/', label: 'Explore' },
  ],
  routePrefixes: ['/'],
};

export const SHARED_NAV_ITEMS = [
  { to: '/friends', label: 'Friends' },
  { to: '/messages', label: 'Msgs', badge: 'unread' },
  { to: '/clubs', label: 'Clubs' },
];

const experienceMap = new Map(EXPERIENCE_CATALOG.map(experience => [experience.id, experience]));

export function getExperienceById(id) {
  return experienceMap.get(id);
}

export function findExperienceByPath(pathname) {
  return EXPERIENCE_CATALOG.find(experience => {
    const prefixes = experience.routePrefixes || [experience.path];
    return prefixes.some(prefix => pathname === prefix || pathname.startsWith(`${prefix}/`));
  }) || DEFAULT_EXPERIENCE;
}

export function isImmersivePath(pathname) {
  return !!EXPERIENCE_CATALOG.find(experience => {
    if (!experience.immersive) return false;
    const prefixes = experience.routePrefixes || [experience.path];
    return prefixes.some(prefix => pathname === prefix || pathname.startsWith(`${prefix}/`));
  });
}
